services:
  - type: web
    name: solde-eleve-api
    env: python
    region: oregon
    plan: free


    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server_flask:app --bind 0.0.0.0:$PORT"

    envVars:
      - key: FLASK_ENV
        value: production

