services:
  - type: web
    name: solde-eleve-api
    env: python
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server_flask:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
